import { Count } from "@sagittal/general"

const TILE_ROW_FOR_EDO: Count = 1 as Count

const DEFAULT_TILE_ROW_COUNT_WITH_ONE_ROW_FOR_EDO_AND_ONE_FOR_SAGITTALS_OR_SUBSET: Count =
    2 as Count

export {
    TILE_ROW_FOR_EDO,
    DEFAULT_TILE_ROW_COUNT_WITH_ONE_ROW_FOR_EDO_AND_ONE_FOR_SAGITTALS_OR_SUBSET,
}
