export { computeRelatedEdosLine } from "./related"
export { computeDiagramLines } from "./diagram"
export { computeEquivalentNotationsLine } from "./equivalence"
export { computeSubsectionHeadingLine } from "./heading"
export { computeApproximationExplanationLine } from "./approximations"
